import { Member } from './types';

export const MEMBERS: Member[] = [
  {
    id: 'davide-cirilli',
    name: 'Davide Cirilli',
    role: 'Informatics Researcher',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac ligula vel diam molestie vehicula non in tellus. Curabitur sed nisl eu lectus convallis feugiat id sed erat. Aliquam lorem ante, interdum vitae pretium non, eleifend sed tellus.',
    github: 'davy592',
    researchInterests: ['Deep Learning', 'Computer Vision', 'Reinforcement Learning', 'Neural Architectures'],
  },
  {
    id: 'mattia-curri',
    name: 'Mattia Curri',
    role: 'Informatics Researcher',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pretium pretium tempor. Ut eget imperdiet neque. In sit amet imperdiet ante. Sed vel varius nulla. Duis interdum luctus nisl, eu cursus mi scelerisque rhoncus.',
    github: 'mattiacurri',
    dblpPid: '433/5477',
    orcid: '0009-0001-0546-7676',
    googleScholarId: 'yrLYcIEAAAAJ',
    researchInterests: ['Big Data Pipelines', 'Data Mining', 'Statistical Modeling', 'Graph Databases'],
  },
  {
    id: 'pierluigi-de-palo',
    name: 'Pierluigi De Palo',
    role: 'Informatics Researcher',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet eleifend sem. Curabitur vel tristique nisl. Mauris ac scelerisque lorem. Sed volutpat nulla id risus pellentesque, vel congue felis elementum.',
    github: 'pierluigi-depalo',
    researchInterests: ['Human-Computer Interaction', 'Data Visualization', 'UX Design', 'Front-End Architectures'],
  },
  {
    id: 'filippo-di-gravina',
    name: 'Filippo Di Gravina',
    role: 'Informatics Researcher',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in ipsum id orci porta dapibus. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Sed porttitor lectus nibh. Praesent sapien massa, convallis a pellentesque nec.',
    github: 'fdigravina',
    dblpPid: '433/5354',
    googleScholarId: 'V5lRA70AAAAJ',
    researchInterests: ['Formal Verification', 'Model Checking', 'Compiler Construction', 'Static Analysis'],
  },
  {
    id: 'francesco-damiano-di-gregorio',
    name: 'Francesco Damiano Di Gregorio',
    role: 'Informatics Researcher',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur aliquet quam id dui posuere blandit. Proin eget tortor risus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque.',
    github: 'nanonani',
    dblpPid: '433/5300',
    googleScholarId: '5ohFWrkAAAAJ',
    researchInterests: ['Quantum Computing', 'Quantum Algorithms', 'Complexity Theory', 'High-Performance Algorithms'],
  },
  {
    id: 'emanuele-fontana',
    name: 'Emanuele Fontana',
    role: 'Informatics Researcher',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur non nulla ut libero vulputate elementum. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Nulla quis lorem ut libero malesuada feugiat.',
    github: 'Fonty02',
    dblpPid: '407/3984',
    orcid: '0009-0008-7400-5820',
    googleScholarId: 'YqUDOJEAAAAJ',
    researchInterests: ['Distributed Systems', 'Cloud Computing', 'Blockchain', 'Network Protocols'],
  },
  {
    id: 'stefano-labianca',
    name: 'Stefano Labianca',
    role: 'Informatics Researcher',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ultricies ligula sed magna dictum porta. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
    github: 'stefanolabianca',
    dblpPid: '437/6235',
    orcid: '0009-0002-9280-4446',
    googleScholarId: 'hEsbpU4AAAAJ',
    researchInterests: ['Natural Language Processing', 'Text Embeddings', 'Semantic Search', 'Transformer Architectures'],
  },
  {
    id: 'mauro-losurdo',
    name: 'Mauro Losurdo',
    role: 'Informatics Researcher',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.',
    github: 'switcha57',
    researchInterests: ['Cryptography', 'Cybersecurity', 'Zero-Knowledge Proofs', 'Secure Computing'],
  },
  {
    id: 'michele-minervini',
    name: 'Michele Minervini',
    role: 'Informatics Researcher',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur aliquet quam id dui posuere blandit.',
    github: 'MicheleMinervini06',
    googleScholarId: 'qDbMAgYAAAAJ',
    researchInterests: ['Heuristic Optimization', 'Meta-Heuristics', 'Combinatorial Search', 'Hybrid AI Systems'],
  },
  {
    id: 'vincenzo-monopoli',
    name: 'Vincenzo Monopoli',
    role: 'Informatics Researcher',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sollicitudin molestie malesuada. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel.',
    github: 'vincy02',
    researchInterests: ['Robot Perception', 'Spatial AI', 'Sensor Fusion', 'Real-time Computer Vision'],
  },
  {
    id: 'andrea-porcelli',
    name: 'Andrea Porcelli',
    role: 'Informatics Researcher',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porttitor lectus nibh. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.',
    github: 'firekern',
    dblpPid: '433/5376',
    orcid: '0009-0001-7828-0757',
    googleScholarId: 'q3kHeygAAAAJ',
    researchInterests: ['Algorithm Design', 'Graph Theory', 'Competitive Programming', 'Discrete Mathematics'],
  },
  {
    id: 'fabio-zippo',
    name: 'Fabio Zippo',
    role: 'Informatics Researcher',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Pellentesque in ipsum id orci porta dapibus.',
    github: 'IXRyu',
    researchInterests: ['Systems Programming', 'Low-level Optimization', 'Competitive Programming', 'C++ Design'],
  },
];
